nestoca/joy

cmd/joy/root.go
internal/build/promote.go
internal/build/promote_test.go
internal/utils/yaml.go

- Also return error when no releases found

fix: Marshal yaml with 2 space indents

---

cmd/joy/environment.go
cmd/joy/project.go
cmd/joy/release.go
cmd/joy/root.go
cmd/joy/secret.go
go.mod
go.sum
internal/build/promote/promote.go
internal/catalog/catalog.go
internal/catalog/catalog_test.go
internal/environment/environment.go
internal/environment/selection/select.go
internal/jac/jac.go
internal/project/list/list.go
internal/release/cross_release_list.go
internal/release/list/list.go
internal/release/promote/promote.go
internal/release/release.go
internal/release/selection/select.go
internal/secret/import.go
internal/secret/seal.go
internal/yml/find_node.go
internal/yml/find_node_test.go

- Add `joy release people` and `joy project people` commands.
- Allow to selectively load aspects (kinds) of catalog and resolve cross-references between entities.

Add jac people integration + selective catalog loading/resolving

---

api/v1alpha1/release.go

We had forgotten those Release properties that are already used by ArgoCD.

fix: Add missing release properties (name, repoUrl, values)

---

.github/workflows/build-test.yaml

Intentionally using `fix` prefix here to force a version bump on merge

fix: Do not run pipeline if only CHANGELOG is updated

---

internal/config/config.go

When using `joy env select` without a config it would error out, and `touch`ing the file made joy segfault.
So the graceful handling code was already present, but the `LoadFile` would get executed outside of `Load` so it would not get invoked.

fix(config): handle missing config file gracefully

---

internal/yml/locking.go

I think it is more confusing for that `# lock` is not handled.

feat: lock, handle both # lock and ## lock

---

internal/git/clean_working_copy.go
internal/yml/merge.go
internal/yml/merge_test.go

Locked elements only present in target yaml were moved to the end of their siblings. We should instead try to preserve their order by looking at keys coming before them and trying to find equivalent insertion position.

fix: preserve order of locked elements

---

Makefile

Or else there is no guarantee what will be executed across different environments.
Also uses the same import convention as other projects
As discussed in https://github.com/nestoca/joy/pull/35#discussion_r1377915933
This is a no-op since joy doesn't use our other packages.

fix: pin build dependencies

---

cmd/lock-migrator/main.go
cmd/lock-migrator/main_test.go
go.mod
internal/yml/locking.go
internal/yml/merge_test.go

- feat: IsLocked considers !lock tag
- refactor: merge_test as table driven tests
- feat: added lock based yaml testing
The Lock-Migrator doesn't have any full-blown test suite as it is meant to be a one-off command as we migrate the catalog to use `!lock` tags. The catalog will need to have a PR opened and reviewed which invalidates the effort of creating a test suite for this temporary command.

feat(PL-1917)/introduce lock tag

---

pkg/catalog/catalog.go
pkg/catalog/catalog_test/catalog_test.go
pkg/catalog/tags.go
pkg/catalog/tags_test.go

This PR adds validation for unknown yaml tags when loading the catalog's release files.
This will allow us to detect errors when users try to `!lock` values in their releases.

fix(PL-2090): validate yaml tags in release files

---

.goreleaser.yaml

Went ahead and added debian package generation in goreleaser via [nfpm](https://goreleaser.com/customization/nfpm/).
@silphid I wasn't sure about which email I should put in the maintainer field, or we could opt to omit this property altogether.
Output of a local goreleaser run:
Locally installing the resulting deb package
Validating proper installation

chore(packages): add deb package generation in goreleaser

---

cmd/joy/root.go

This check makes it so that `joy help` will run without a catalog configured. 
Without something like this, the `config.CheckCatalogDir(cfg.CatalogDir)` function on at the end of the `PersistentPreRunE` will run when on `joy help`, and an error will be printed to the console instead of the help.

fix(help): run help without invoking pre run checks

---

LICENSE

Joy is open source and as such is missing a LICENSE file based on standard MIT licensing.

doc(PL-2098): add missing LICENSE

---

cmd/lock-migrator/main.go

The lock migrator forgot to check if a file had a yaml extension before processing it. Adding that check so it doesn't modify json files needlessly or break on other file types.

fix(PL-2110): add lock migrator yaml file extension check

---

.github/workflows/build-test.yaml

Note that the action is the same code as nestoca/conventional-changelog-action@releases/v4, but we this way nobody can change the code and tag under our feet.

fix(PL-1906): gha, fix handling of BREAKING

---

cmd/joy/secret.go
go.mod
internal/secret/seal.go

This PR makes the `joy secret seal` command compatible with unix pipes.
This makes sealing the content of files easier, and makes joy easier to script with.
Example:
```
cat credentials.json | joy secret seal -e qa | pbcopy
```

feat(PL-2290): allow secrets to be sealed from stdin

---

internal/secret/seal.go

When outputting the sealed secret to a file or to any unix pipe, we do not want to print the newline.
Newlines are for humans. We are in machine world now.

fix(PL-2290): do not emit newline at end of sealed secret in non-ttl mode

---

cmd/joy/release.go
internal/config/config.go
internal/release/render/render.go
internal/release/render/render_test.go
pkg/values.go

This replicates the ApplicationSet defaults in release rendering. The only omission is `release.spec.versionKey` because it is not captured in the v1alpha1.Release definition. However nobody uses it the catalog so its ok to omit for now.

fix/PL 2314/replicate appset behaviour in release render

---

internal/config/config.go
pkg/config.go

This change is being made so that the `joy-generator` can conveniently load joy catalog configuration.
This will allow the joy-generator to use values set in the catalog instead of hardcoding specific defaults/behaviour.

feat(PL-2372): add joy.LoadCatalogConfig to joy sdk

---

internal/git/git.go

@jsbejeau is using global commit hooks, which is interfering with committing the changes with `joy release promote.`
Context: https://nestomortgage.slack.com/archives/C04ADN73SPL/p1708474214393809?thread_ts=1708468838.434969&cid=C04ADN73SPL

fix: git, ignore hooks when committing

---

internal/diagnostics/executable.go
internal/diagnostics/executable_test.go

Otherwise we depend on the state of brew's cache.

fix: tell people to run `brew update` first

---

internal/config/config.go

I have renamed the file to `joy.yaml` as discussed in https://github.com/nestoca/joy/pull/88
I also have tested using a symlink and it was handled gracefully
by `joy` as-is.
So we can just do: https://github.com/nestoca/catalog/pull/597
And delete the symlink in a few months or so.

feat(PL-2419): add support for alternate names for catalog/joy.yaml

---

api/v1alpha1/project.go
cmd/joy/release.go

Note that the repositorySubdirectory field was not used.
https://github.com/nestoca/catalog/pull/692 must be merged after.

fix(PL-2424): filter git diff/logs correctly in mono-repos

---

.github/workflows/build-test.yaml

Publish step is currently failing:
https://github.com/nestoca/joy/actions/runs/8116624287/job/22187126046

fix(PL-2247): GoRelease github token

---

api/v1alpha1/project.go
internal/github/pull_request_provider.go
internal/release/promote/github_codeowners.go
internal/release/promote/github_codeowners_test.go
internal/release/promote/perform.go
internal/release/promote/promotion.go
internal/release/promote/test/integration_test.go
internal/release/promote/test/promotion_test.go

Example: https://github.com/nestoca/catalog/pull/1095
```
$ JOY_DEV_SKIP_VERSION_CHECK=1 go run ./cmd/joy release promote --dry-run --skip-catalog-update --draft --no-prompt --source qa --target production creditreports
Promote creditreports 0.65.0 -> 0.65.0 (qa -> production)
| Release | Diff | Source: qa | Target: production |
|:---|:---|:---|:---|
| `creditreports` | [Downgrade](https://github.com/nestoca/creditreports/compare/api/v0.65.0...api/v0.65.0) | 0.65.0 <br> [Argo CD](https://argocd.platform.nesto.ca/applications/argocd/qa-creditreports) <br> [Datadog](https://app.datadoghq.com/logs?query=env%3Aqa%20service%3Acreditreports&cols=env%2Cservice) | 0.65.0 <br> [Argo CD](https://argocd.platform.nesto.ca/applications/argocd/production-creditreports) <br> …
```

feat(PL-2247): add labels and CODEOWNERS to PR

---

internal/release/promote/perform.go
internal/release/promote/perform_test.go

Fix bug where releaseInfo that did not have Project would have its project derefenced

fix(PL-2477): fix nil deref bug in joy perform

---

internal/release/promote/inject_pr_links.go
internal/release/promote/inject_pr_links_test.go
internal/release/promote/perform.go
internal/release/promote/test/promotion_test.go

This is a fix to expand PR numbers (such as "#123") in commit messages of different projects into explicit PR links, because otherwise GitHub will automatically convert those PR numbers that it finds in promotion PR description into links to PRs within the catalog repository, whereas those PRs are actually located in the project repositories.
Requires this other PR to be merged before:
https://github.com/nestoca/catalog/pull/1161
Check both `#32` links below, first is automatically converted by GH to a link that points to PR `#32` on this `joy` repo (incorrect!), second is explicitly pointing to correct `audittrail` repo.
| Message | Author | Commit |
|:---|:---|:---|
| Merge pull request #32 from nestoca/chore/PL-2275/migrate-audittrail-production | @j-martin | …

fix(PL-2247): expand pr numbers to explicit links

---

cmd/joy/release.go
internal/release/promote/perform.go
internal/release/promote/promotion.go

A better name is more than welcome. This is similar to a `--dry-run` (preview, no PR, etc.), but it writes the changes to the local filesystem.
We joked around calling it `--moist-run`. I need this change for my bulk `!lock`ing. So there it is.

feat(PL-2460): add `--local-only` mode

---

cmd/joy/environment.go
cmd/joy/project.go
cmd/joy/release.go
cmd/joy/root.go
internal/config/flags.go
internal/environment/configure_selection.go
internal/git/clean_working_copy.go
internal/jac/jac.go
internal/project/list.go
internal/release/configure_selection.go
internal/release/list/list.go
internal/release/promote/git_provider.go
internal/release/promote/promotion.go
internal/release/promote/shell_git_provider.go
internal/release/promote/test/promotion_test.go

ensures the catalog is at origin head
Changing skip-catalog-update to a global flag 
Moving the check of skipCatalogUpdate to PreRun of the command instead of the specific actions

fix(PL-2463): ensure catalog is at origin head

---

internal/yml/merge.go
internal/yml/merge_test.go
internal/yml/tags.go

This PR adds `!local` annotations for values that should be locked, but should not have their structure promoted across environment boundaries.

feat(PL-2418): add !local tag annotation

---

internal/config/config.go

This fix skips non-yaml-persisted fields when merging catalog configs using reflection, so that user settings don't get saved back to catalog config. This is an OK fix for now, but we'll soon refactor all that to properly isolate catalog configs from user preferences.

fix(PL-2574): should not save selection to catalog config

---

cmd/joy/release.go
internal/config/config.go
internal/release/list/list.go
internal/release/promote/interactive_prompt_provider.go
internal/release/promote/promotion.go
internal/release/promote/prompt_provider.go
internal/release/promote/test/integration_test.go
internal/release/promote/test/promotion_test.go

Adds `--narrow` and `--wide` column modes to `joy rel ls` and `joy rel prom`.  Defaults are as follow and can be overridden in user's `.joyrc` file:
```
columnWidths:
narrow: 20
normal: 40
wide: 80
```

feat(PL-2575)/narrow-wide-column-modes

---

cmd/joy/build.go
internal/build/promote.go
internal/build/promote_test.go
internal/release/cross/release_list.go

1d3c9fb4350cc5a18e33bc78e15ea59e02da57d5 broke `build promote`    in a few ways:
- Did not have a writer
- Releases items now are in an array where the index is set per environment. Not all environments may have a release. Note: Why not using a map?

fix(PL-2582): fix build promote

---

cmd/joy/release.go
internal/git/clean_working_copy.go
internal/git/git.go
internal/release/list/list.go

See documentation [here](https://nestoca.atlassian.net/wiki/spaces/DEVOPS/pages/2669936744/Internal+Developer+Platform#How-to-create-your-own-joy-extension-scripts) for an example script that uses `joy rel ls --json`.
Actually, here it is:
```
#!/usr/bin/env bash
joy release list --env staging --json 2>/dev/null | 
jq -r '.crossReleases[] | select(.name == "accounts") | .releases[] | select(.status == "ahead") | "\(.metadata.name): \(.version)"'
```
It would be great to internally do the equivalent of `2>/dev/null` for `--json` output, otherwise it clutters up the output (even if it's now sent to `stderr`, the user still sees it).

feat(PL-2602): joy rel ls --json

---

cmd/joy/environment.go
cmd/joy/project.go
cmd/joy/release.go
cmd/joy/root.go
cmd/joy/root_test.go
internal/git/clean_working_copy.go

This PR updates the EnsureCleanAndUpToDateWorkingCopy function such that it will update the config and catalog context objects.
The one issue with this approach is that we don't run the same checks as the root, such as checking joy min Versions, etc.
However we weren't doing so before, so this is not a regression. But we will need to think on it for a future task.

fix(PL2614): update catalog and config on catalog pull

---

internal/yml/merge.go
internal/yml/merge_test.go

fix(!local): local nodes must be removed from source before merge

---

cmd/joy/build.go
cmd/joy/release.go
cmd/joy/release_render_test.go
internal/prompt.go
internal/release/render/render.go
internal/release/render/render_test.go
internal/release/validate/validate.go
internal/release/validate/validate_test.go
pkg/catalog/catalog.go
pkg/helm/helm.go
pkg/helm/pull_renderer_mock.go

- **feat(PL-2736): joy release render support all and all-env flags**
- **fix(PL-2736): include both git-ref and diff-ref catalog in known state**
With this PR we will be able to view the diff of the entire catalog's releases rendered via one command:
```
joy release render --all-envs --all --diff-ref REF
```

feat/PL 2736/render many releases

---

api/v1alpha1/environment.go
api/v1alpha1/project.go
api/v1alpha1/release.go
internal/yml/decoder.go
pkg/catalog/catalog_test.go
pkg/catalog/testdata/invalid-crd-schema/joy.yaml
pkg/catalog/testdata/invalid-crd-schema/projects/testing.yaml

We should use strict decoding of yaml documents when parsing catalog CRD-Like objects. This way if users add unknown properties such as typos, they can be caught early.
In the current catalog many projects have the typo `repositorySubPaths` instead of the expected `repositorySubpaths`, not `Paths` instead of `paths`.
This means that for some projects the git diff and git log commands do not work as expected.

fix(PL-660): stricter crd decoding

---

internal/ignore/ignore.go
internal/release/promote/perform.go
internal/release/promote/pr_rendering.go
internal/release/promote/pr_rendering_test.go
internal/release/promote/promotion.go

This PR adds a new field to the ReleaseInfo struct "ValuesChanged".
This will allow users to highlight which releases contain configuration changes in the PR body.

feat(PL-2604): add ConfigChanges to ReleaseInfo

---

api/v1alpha1/environment.go
api/v1alpha1/project.go
api/v1alpha1/release.go
internal/schema.go
internal/schema_test.go

Not too long ago, schemas were added to represent the Joy CRDs. However the original implementation was wrong in that it would validate against the already serialized Go struct instead of the files root yaml node.
This would cause information loss and things to not get picked up by the schema validation.
For example with this change the internal tests started failing because `versionKey` which is an unknown property was being caught and it previously was not.
```
loading catalog: validating releases:
- podinfo/demo: validation: error: #release.spec.versionKey: field not allowed
- podinfo/dev: validation: error: #release.spec.versionKey: field not allowed
- podinfo/platform: validation: error: #release.spec.versionKey: field not allowed
- podinfo/qa: validation: error: …
```

fix(PL-660): validate crd schemas against file content not deserialized representation

---

api/v1alpha1/release.go
internal/release/render/render.go
internal/release/render/render_test.go
pkg/helm/cache.go

This PR allows mappings to be configured per chart both at the reference level within the catalog's joy.yaml configuration and within the release.
This will allow us to move the `image.tag` mapping from the global configuration to being specific to the `generic` chart. It will allow us to map our application version to different mappings for different charts.
This feature replaces the intent of `versionKey` that was broken but used in the appset.

feat(PL-2834): support mappings per chart and release

---

.github/workflows/build-test.yaml

Note that we may need/want to use a different GH app to publish.

fix(build): use proper token
